Feature/consumables
ldcinventory/ldcgc-backend pull request #18
Opened 2024-01-16 19:27 UTC by dpanait6

2024-01-20 09:08 UTC, srello requested changes

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/controller/resources/ConsumableController.java
> +    @GetMapping("/{consumableId}")
Falta el swagger e todos los métodos del controller.

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/controller/resources/impl/ConsumableControllerImpl.java
> +    public ResponseEntity<?> testAccessWithCredentials() {
Los métodos test se pueden borrar

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/db/repository/resources/ConsumableRepository.java
> +    //Boolean create(Consumable consumable);
Los métodos comentados que no se usen pueden borrarse

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/exception/ApiExceptionHandler.java
> +            .endpoint(ex.getAllValidationResults().get(0).getMethodParameter().getMethod().getName())
Puede ser que el get(0) lo hayas cambiado porque salía error antes de actualizar la versión de java? en ese caso, mejor volver a dejarlo como estaba: getFirst()

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/payload/mapper/resources/consumable/ConsumableMapper.java
> +    //@Mapping(source = "status.name", target = "status")
borrar el codigo comentado de esta clase

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/payload/mapper/resources/tool/ConsumableMapper.java
> +public interface ConsumableMapper {
hay 2 ConsumableMapper. Probablemente sobre uno, y ese parece estar en el directorio incorrecto. Revisarlo y borrarlo.

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +            return Constructor.buildResponseObject(HttpStatus.OK, consumableEntity);
mapear a DTO en la respuesta

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +            return Constructor.buildResponseMessage(HttpStatus.NOT_MODIFIED, e.getMessage());
Ver si es el HttpStatus correspondiente

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +    public ResponseEntity<?> createConsumable(ConsumableDto consumable) {
Hay que comprobar que el create no reciba un codigo de barras existente. Si lo hace, hay que sacar un error, ya que los códigos de barras no pueden repetirse.

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +                //System.out.println("Consumable: " + consumable.getName() + " - " +consumable.getDescription());
borrar codigo comentado

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +            return Constructor.buildResponseMessagePageable(HttpStatus.OK, String.format(getInfoMessage(CONSUMABLE_LISTED), consumablePaged.getTotalElements()), response);
No hace falta crear un objeto nuevo, el objeto Page tiene todos los elementos necesarios y puede devolverse en la respuesta.

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +                consumablePaged = consumableRepository.findByNameContainingOrDescriptionContaining(filterString, filterString, pageable);
Puedes poner que el filterString sea "" por defecto en el controller y así no te hace falta este if/else. Si el filterString está vacío y la query está bien montada, se incluyen todos.
Así limpiamos el código y lo hacemos más legible

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +    public ResponseEntity<?> listConsumables(Integer pageIndex, Integer sizeIndex, String filterString) {
Quizás por ser consistentes sea buena idea incluir un sortString y diferentes categorías de filtros. Ver ToolServiceImpl.getAllTools

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +    public ResponseEntity<?> updateConsumable(ConsumableDto consumableDto) {
Hay que comprobar si ha cambiado el codigo de barras. Si lo ha hecho y el nuevo está repetido hay que sacar un error, ya que ese campo debe ser único

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +            return Constructor.buildResponseMessage(HttpStatus.NOT_MODIFIED, e.getMessage());
Ver si el codigo de error NOT_MODIFIED es el correcto

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +        } else {
este else no hace falta porque tienes un return arriba.

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +            return Constructor.buildResponseMessage(HttpStatus.OK, String.format(getErrorMessage(CONSUMABLE_NOT_FOUND), consumableId));//String.format(getErrorMessage(CONSUMABLE_NOT_FOUND), consumabl
borrar codigo comentado

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +        return null;
no debería retornar null

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +    private List<ConsumableDto> convertExcelToConsumable(List<ConsumableExcelDto> consumablesExcel){
este código es correcto, pero hace muchas consultas a BBDD, podría realentizar el proceso en caso de haber muchos consumibles.
Quizás dejar un //TODO: Optimizar si el proceso es lento

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/tool/ConsumableService.java
> +public interface ConsumableService {
Esta clase está repetida, por el directorio parece que esta es la incorrecta. Eliminarla.

2024-01-20 09:08 UTC, srello commented on src/main/java/org/ldcgc/backend/util/common/ConsumableExcelProcess.java
> +        return ConsumableExcelDto.builder()
Estaría muy bien controlar errores al parsear el excel, e indicar al usuario la fila y columna en la que está el error.
Normalmente, los errores se produciran porque te venga un tipo de dato o un valor incorrectos.

2024-01-20 09:08 UTC, srello commented on src/test/java/org/ldcgc/backend/controller/resources/tool/ToolControllerImplTest.java
> +        assertEquals(ToolDto.class, ((List<ToolDto>)((Response.DTO) Objects.requireNonNull(response.getBody())).getData()).stream().findFirst().getClass());
actualizar la version de java y dejar el getFirst()

2024-01-20 09:08 UTC, srello commented on src/test/java/org/ldcgc/backend/service/resources/tool/ToolServiceImplTest.java
> +        assertEquals(ToolDto.class, ((List<ToolDto>) responseBody.getData()).get(0).getClass());
actualizar la version de java y dejar el getFirst()

2024-01-20 09:08 UTC, srello commented on src/test/java/org/ldcgc/backend/service/users/UserServiceImplTest.java
> +        assertEquals(headerPayLoad, response.getHeaders().get("x-header-payload-token").get(0));
actualizar la version de java y dejar el getFirst()

2024-01-20 09:08 UTC, srello commented on src/test/java/org/ldcgc/backend/service/users/UserServiceImplTest.java
> +        assertEquals(signature, response.getHeaders().get("x-signature-token").get(0));
actualizar la version de java y dejar el getFirst()

2024-01-20 09:08 UTC, srello commented on src/test/java/org/ldcgc/backend/service/users/UserServiceImplTest.java
> +        assertEquals(response.getHeaders().get("x-header-payload-token").get(0), headerPayLoad);
actualizar la version de java y dejar el getFirst()

2024-01-20 09:08 UTC, srello commented on src/test/java/org/ldcgc/backend/service/users/UserServiceImplTest.java
> +        assertEquals(response.getHeaders().get("x-signature-token").get(0), signature);
actualizar la version de java y dejar el getFirst()

2024-02-02 11:37 UTC, srello requested changes, later dismissed

2024-02-02 11:37 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/consumable/impl/ConsumableServiceImpl.java
> +            return Constructor.buildResponseMessage(HttpStatus.OK, "Record deleted");
En este return y en el del catch mejor usar mensajes de la clase Messages en vez de hardcodearlo

2024-02-02 11:37 UTC, srello commented on src/main/java/org/ldcgc/backend/controller/resources/ConsumableController.java
>      //  Delete consumable DELETE
Borrar este TODO, ya está todo hecho

2024-02-02 11:37 UTC, srello commented on src/main/java/org/ldcgc/backend/controller/resources/ConsumableController.java
>      //@PreAuthorize("hasAnyRole('USER', 'MANAGER', 'ADMIN')")
Descomentar esta línea!!! Sino nos quedamos sin Auth

2024-02-03 23:52 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/util/common/ConsumableExcelProcess.java
> +        return ConsumableExcelDto.builder()
Lo dejo como TODO dentro del catch :)

2024-02-03 23:56 UTC, mindOf-L approved these changes

2024-02-04 00:00 UTC, mindOf-L approved these changes

2024-02-04 01:09 UTC, mindOf-L requested changes
Esperando a los tests E2E de Dan.

2024-02-06 15:22 UTC, closed without merging

2024-02-06 15:23 UTC, mindOf-L commented
Cerrada. Lista la PR con las correcciones solicitadas y las pruebas hechas: https://github.com/ldcinventory/ldcgc-backend/pull/21