Feature/tool post
ldcinventory/ldcgc-backend pull request #4
Opened 2023-12-02 09:00 UTC by srello

2023-12-02 17:20 UTC, mindOf-L requested changes
Limpia los imports en todo el proyecto. Primero edita la configuración para no usar asteriscos en los imports: https://stackoverflow.com/a/3348855/4978689

Y después haz limpieza de imports con Optimize Import:
<img width="444" alt="image" src="https://github.com/ldcinventory/ldcgc-backend/assets/22920275/79641063-584f-4d94-a363-80d0446a1aec">

2023-12-02 17:20 UTC, mindOf-L commented on pom.xml
> +			<version>4.1.2</version>
Parametriza esta versión en la parte superior como property y así unificas las versiones de apache. Usa la última versión. Esta es de 2020: https://mvnrepository.com/artifact/org.apache.poi/poi

2023-12-02 17:20 UTC, mindOf-L commented on pom.xml
> +			<version>4.1.2</version>
Mismo que de más arriba.

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
> +    @PreAuthorize("hasAnyRole('ADMIN')")
Usa la constante ADMIN_LEVEL

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
> +    //@PreAuthorize("hasAnyRole('ADMIN')")
Si no hay @PreAuthorize cualquier usuario, incluso sin token, podría usar este endpoint

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
> +    @PreAuthorize("hasAnyRole('ADMIN')")
Usa la constante ADMIN_LEVEL

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
> +    @PreAuthorize("hasAnyRole('ADMIN')")
Usa la constante ADMIN_LEVEL

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/resources/tool/impl/ToolServiceImpl.java
> +import static org.ldcgc.backend.util.retrieving.Message.ErrorMessage.*;
intenta no hacer import con asterisco. Sigue esta configuración para Intellij https://stackoverflow.com/a/3348855/4978689

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/resources/tool/impl/ToolServiceImpl.java
> +        return Constructor.buildResponseObject(HttpStatus.OK, ToolMapper.MAPPER.toDto(tool));
Es necesario mapear el objeto cuando se hace delete?

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/resources/tool/impl/ToolServiceImpl.java
> +        return toolsExcel.stream()
mmm crees que se podría mejorar la lectura del código construyendo el objeto fuera del return? sé que Intellij te propone hacer un return directamente, sin construir el objeto aparte. pero qué te parece la legibilidad de este tocho? 😂

2023-12-02 17:20 UTC, mindOf-L commented on src/main/resources/csv-ldcgc8.zip
no subas este zip. bórralo del repositorio, haz commit y después añade ".zip" en el .gitignore

2023-12-02 17:20 UTC, mindOf-L commented on src/test/java/org/ldcgc/backend/controller/resources/tool/ToolControllerImplTest.java
> +    //TODO: Fix test and add excel tests, get all pageable tests
Si este test está pendiente significa que la rama no se borra?

2023-12-02 17:20 UTC, mindOf-L commented on src/test/java/org/ldcgc/backend/service/tool/impl/ToolServiceImplTest.java
> +import static org.mockito.Mockito.*;
Recuerda hacer un Optimize import de todo el proyecto cuando configures lo del asterisco en el IntelliJ, y así quitas todos estos imports con asterisco y eliminas también los imports que no sirven 😊

2023-12-02 17:20 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
por favor, documenta estos endpoints para Swagger. fíjate en la documentación de otros controllers (por ej: AccountController: https://github.com/ldcinventory/ldcgc-backend/blob/develop/src/main/java/org/ldcgc/backend/controller/users/AccountController.java)

2023-12-02 17:48 UTC, mindOf-L requested changes
Revisa estos comentarios, please 🙏

2023-12-02 17:48 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/payload/dto/excel/ToolExcelDto.java
> +@Value
esta anotación añade funcionalidad no indispensable según tu uso de la clase en el proyecto. modifícala por un @Getter de la librería de Lombok

2023-12-02 17:48 UTC, mindOf-L commented on src/main/resources/application.yml
> +  port: ${TOMCAT_PORT:8081}
Si cambias este puerto por defecto, cambia el readme. Los chicos de frontend necesitan saber a qué puerto apuntar.

2023-12-02 17:48 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/location/impl/LocationServiceImpl.java
> +                .orElseThrow(() -> new RequestException(HttpStatus.NOT_FOUND, getErrorMessage(LOCATION_NOT_FOUND)
Idea, mete un TODO en RequestException para incluir objetos a través de constructor, y referencia este return para un futuro refactor.

2023-12-02 17:48 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/groups/impl/GruopServiceImpl.java
> +                .orElseThrow(() -> new RequestException(HttpStatus.NOT_FOUND, getErrorMessage(GROUP_NOT_FOUND)
Idea, mete un TODO en RequestException para incluir objetos a través de constructor, y referencia este return para un futuro refactor.

2023-12-02 17:48 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/category/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new RequestException(HttpStatus.NOT_FOUND,
Idea, mete un TODO en RequestException para incluir objetos a través de constructor, y referencia este return para un futuro refactor.

2023-12-03 19:35 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/tool/impl/ToolServiceImpl.java
> +        return toolsExcel.stream()
No veo que haya mucha diferencia entre devolver el objeto directamente y hacer una variable antes de devolverlo, la redibilidad es practicamente la misma. O hablas de refactorizarlo de alguna otra manera?

2023-12-03 19:37 UTC, srello commented on src/test/java/org/ldcgc/backend/controller/resources/tool/ToolControllerImplTest.java
> +    //TODO: Fix test and add excel tests, get all pageable tests
Puedo trabajar en la misma rama o abrir otra, me es igual. He saltado un par de test para desbloquear a front.

2023-12-03 19:38 UTC, srello commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
Te parece bien si hago un TODO para documentarlos con los tests?

2023-12-03 19:39 UTC, srello commented on src/main/resources/application.yml
> +  port: ${TOMCAT_PORT:8081}
Queria cambiarlo solo para mi local, lo añado al .gitignore?

2023-12-03 22:25 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/resources/tool/impl/ToolServiceImpl.java
> +        return toolsExcel.stream()
Hablaba de legibilidad, para separar un poco. Veo que haces muchas llamadas a base de datos en el propio constructor para insertar objetos, ej:
groupsService.findGroupInListByName(toolExcel.getGroup(), groups)
locationService.findLocationInListByName(toolExcel.getLocation(), locations)

(Creo) Lo ideal sería hacer todas esas llamadas fuera del constructor, para controlar posibles errores y pasarle directamente el objeto instanciado. Sé que es verboso, pero no crees que sería algo más legible y mantenible de cara al futuro?

2023-12-03 22:26 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
Perfect.

2023-12-03 22:31 UTC, mindOf-L commented on src/main/resources/application.yml
> +  port: ${TOMCAT_PORT:8081}
No hace falta añadirlo al gitignore, solo no lo subas :) tendrías que hacer una subida restaurando el código anterior

2023-12-03 22:32 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
Cuando lo tengas avisas y marcas esta conversación como resuelta :)

2023-12-03 22:32 UTC, mindOf-L commented on src/test/java/org/ldcgc/backend/controller/resources/tool/ToolControllerImplTest.java
> +    //TODO: Fix test and add excel tests, get all pageable tests
Mejor otra rama e integramos esta. Así no solo desbloqueamos a front, evitamos la PR de Dan y aglutinar mucho trabajo.

2023-12-03 22:34 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/controller/resources/ToolController.java
> +    @PreAuthorize("hasAnyRole('ADMIN')")
Ojo con las constantes ADMIN_LEVEL que has puesto y demás. Fíjate por ejemplo en:
https://github.com/ldcinventory/ldcgc-backend/blob/6cdd72b20437376323205b0c535a2aacc3619c1e/src/main/java/org/ldcgc/backend/controller/users/VolunteerController.java#L171

Las constantes ya incluyen el hasAnyRole como constante. Te lo reviso y hago subida :)

2023-12-04 19:23 UTC, srello commented on src/main/java/org/ldcgc/backend/service/resources/tool/impl/ToolServiceImpl.java
> +        return toolsExcel.stream()
Hecho!

2023-12-04 19:23 UTC, srello commented on src/main/java/org/ldcgc/backend/payload/dto/excel/ToolExcelDto.java
> +@Value
hecho!

2023-12-04 19:23 UTC, srello commented on src/main/resources/application.yml
> +  port: ${TOMCAT_PORT:8081}
hecho!

2023-12-05 07:08 UTC, mindOf-L approved these changes
Hechos algunos cambios para ajustar los objetos devueltos en Tools, que no devolvían mensaje de estado junto a la parte de Data en el objeto Response.
Cuando hacemos DELETE, no es necesario devolver el objeto, ya que front no lo mapeará de ningún modo, y al no existir en base de datos no tiene sentido devolverlo tampoco. Lo he cambiado por un mero mensaje de "Tool deleted" y listo (modificando el test oportunamente).
Te he optimizado los imports y he limpiado un par de anotaciones. Échale un vistazo

2023-12-05 07:46 UTC, merged