EULA + Volunteers, Controller Tests (1st)
ldcinventory/ldcgc-backend pull request #6
Opened 2023-12-19 19:35 UTC by mindOf-L

2023-12-20 10:57 UTC, srello requested changes

2023-12-20 10:57 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/AccountServiceImpl.java
> +        if(FALSE.equals(Boolean.parseBoolean(actualRequest.getHeader("skip-eula")))) {
Esté código es casi idéntico a AuthTokenFilter linea 74. Se puede refactorizar y sacar una funcion? Así cumplimos con el principio DRY

2023-12-20 10:57 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/EulaServiceImpl.java
> +            .url("https://docs.google.com/document/d/e/2PACX-1vTMAT1BQXKqh0zNooCJPFCWHYP7lXUGXdVemuGbZt9DgkZIoVoBwLPnx7DBzjwyJ0LxCpNfRKUA3nfl/pub?embedded=true")
las urls hardcodeadas mejor sacarlas a un fichero de propiedades ¿?

2023-12-20 10:57 UTC, srello commented on src/test/java/org/ldcgc/backend/base/mock/MockedUserDetails.java
> +package org.ldcgc.backend.base.mock;
ver si podriamos usar podam para esto, quizas no sea necesario crear a mano todos estos datos de prueba

2023-12-20 10:57 UTC, srello commented on src/test/java/org/ldcgc/backend/service/users/AccountServiceImplTest.java
> +
marcar con TODO y sacar tarea en trello

2023-12-20 11:08 UTC, mindOf-L commented on src/test/java/org/ldcgc/backend/service/users/AccountServiceImplTest.java
> +
Al ser 1 primera PR, no haría falta, ya que la siguiente subiré todos los demás tests de servicio que me faltan.

2023-12-20 11:13 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/AccountServiceImpl.java
> +        if(FALSE.equals(Boolean.parseBoolean(actualRequest.getHeader("skip-eula")))) {
jeje en qué se parecen? No son los mismos casos, ni los mismos retornos.

Código de `AccountServiceImpl.java`:
```
if(FALSE.equals(Boolean.parseBoolean(actualRequest.getHeader("skip-eula")))) {

// get eula details (standard user)
if (userEntity.getAcceptedEULA() == null)
    return Constructor.buildResponseObjectLocation(HttpStatus.FORBIDDEN, Messages.Error.EULA_STANDARD_NOT_ACCEPTED, Messages.App.EULA_ENDPOINT, headers);

// get eula details (manager)
if((userEntity.getRole().equalsAny(ROLE_MANAGER, ROLE_ADMIN))
    && userEntity.getAcceptedEULAManager() == null)
    return Constructor.buildResponseObjectLocation(HttpStatus.FORBIDDEN, Messages.Error.EULA_MANAGER_NOT_ACCEPTED, Messages.App.EULA_ENDPOINT, headers);
}
```

Código de `AuthTokenFilter.java`:
```
// skip eula if header or exempted endpoint (i.e.: get/accept eula)
if(notExemptedEndpoint(request.getMethod(), request.getRequestURI())
    && FALSE.equals(Boolean.parseBoolean(request.getHeader("skip-eula")))) {

    // get eula details (standard user)
    if (userDetails.getAcceptedEULA() == null)
        throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.EULA_STANDARD_NOT_ACCEPTED);

    // get eula details (manager)
    if((userDetails.getAuthorities().contains(new SimpleGrantedAuthority(ROLE_MANAGER.name())) ||
        userDetails.getAuthorities().contains(new SimpleGrantedAuthority(ROLE_ADMIN.name())))
        && userDetails.getAcceptedEULAManager() == null)
        throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.EULA_MANAGER_NOT_ACCEPTED);
}
```

Si te fijas son diferentes comprobaciones, además de los diferentes retornos. De hecho, en la parte de `AccountServiceImpl.java` necesito devolverlo de esa forma, porque meto en las cabeceras el token que necesitaría el usuario para poder hacer PUT y aceptar los términos y condiciones.

2023-12-20 11:17 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/EulaServiceImpl.java
> +            .url("https://docs.google.com/document/d/e/2PACX-1vTMAT1BQXKqh0zNooCJPFCWHYP7lXUGXdVemuGbZt9DgkZIoVoBwLPnx7DBzjwyJ0LxCpNfRKUA3nfl/pub?embedded=true")
Arreglado!

2023-12-20 11:19 UTC, mindOf-L commented on src/test/java/org/ldcgc/backend/base/mock/MockedUserDetails.java
> +package org.ldcgc.backend.base.mock;
Aprueba la PR y en la siguiente te lo limpio, aprovechando que estoy usando PodamFactory para los servicios

2023-12-21 07:29 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/AccountServiceImpl.java
> +        if(FALSE.equals(Boolean.parseBoolean(actualRequest.getHeader("skip-eula")))) {
No me refería a todo el if entero, sino al propio condicional:

 FALSE.equals(Boolean.parseBoolean(request.getHeader("skip-eula")))

Aunque es algo menor.

2023-12-21 07:30 UTC, srello commented on src/test/java/org/ldcgc/backend/base/mock/MockedUserDetails.java
> +package org.ldcgc.backend.base.mock;
Ok, dejamos un TODO y tarea en trello?

2023-12-21 07:31 UTC, srello approved these changes

2023-12-21 07:54 UTC, merged