Final -> Users + Volunteers + Eula (Tests, Functionality)
ldcinventory/ldcgc-backend pull request #8
Opened 2024-01-03 14:04 UTC by mindOf-L

2024-01-03 18:20 UTC, srello requested changes

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/db/model/users/Volunteer.java
> +public class Volunteer implements Serializable {
Ver si hay una solución mejor que no implique hacer todos los objetos serializables

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        final Integer originVolunteerId = Optional.ofNullable(userEntity.getVolunteer()).map(Volunteer::getId).orElse(null);
Usar optional en lugar de null

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(volunteer == null)
usar orElseThrow

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(checkUserVolunteer != null && !checkUserVolunteer.getId().equals(userEntity.getId()))
Usar optional

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(category == null)
Usar orElseThrow

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(group == null)
Usar orElseThrow

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        if(checkUser != null && !checkUser.getId().equals(userEntity.getId()))
Usar optional

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        if(userFromToken.getRole().equals(ERole.ROLE_MANAGER)) {
usar guard clause para evitar mucha indentacion

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        // map the whole User with password encoded
En general esta clase tiene muchos comentarios. En la medida de lo posible, es mejor escribir código que se documente sólo usando buenos nombres para las variables y funciones, y sacando fragmentos de código a su propia función cuando sea necesario.

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
En principio ya se copia en el mapper. Si hay que personalizar el copiado, mejor hacer una funcion en el mapper e indicarla con el qualifiedByName.

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
>          Volunteer volunteerEntity = volunteerRepository.findByBuilderAssistantId(volunteerId).orElseThrow(() ->
El volunteerId no es diferente del builder assistant id? no se debería usar el findById?

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getBuilderAssistantId() != null) {
chequear tambien si el id de BA del DTO es diferente al de la entidad para ahorrar consultas a BBDD y simplificar la lógica

2024-01-03 18:20 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
igual que antes, esto es mejor gestionarlo en el mapper si se puede

2024-01-03 18:45 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/db/model/users/Volunteer.java
> +public class Volunteer implements Serializable {
rollback hecho!

2024-01-03 18:45 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        final Integer originVolunteerId = Optional.ofNullable(userEntity.getVolunteer()).map(Volunteer::getId).orElse(null);
El estilo que sugieres sería así:

`final Optional<Integer> id = Optional.ofNullable(entity.getX()).map(X::getId);`

Y después en el if de más abajo sería:

`if(id.isEmpty())` en vez de `if(id == null)`

Lo sugieres por legibilidad? Por estilo...??

2024-01-03 18:46 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(volunteer == null)
Bien visto! Cambiado!

2024-01-03 18:56 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
>          Volunteer volunteerEntity = volunteerRepository.findByBuilderAssistantId(volunteerId).orElseThrow(() ->
No tiene sentido buscarlo por el id de Base de datos, ya que a juzgar por las acciones del usuario, buscarán por su id del builder assistant, que no es el ID principal en la base de datos. Consulta los diseños o bien la especificación de la entidad Volunteer.

2024-01-03 18:57 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
>          Volunteer volunteerEntity = volunteerRepository.findByBuilderAssistantId(volunteerId).orElseThrow(() ->
Eso sí, para ahorrar disgustos en la lectura, cambio volunteerId por builderAssistantId.

2024-01-03 19:17 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
El mapper no puede solucionar esto, dado que es un enlace entre entidades y no tiene capacidad de introducir una entidad anidada, siendo esta la contenedora, dentro del objeto una vez mapeado.

Si hay algo que se pueda hacer, dame la solución y la implemento, dado que hacer, por ejemplo:
`@Mapping(target = "availability.volunteer", source = ".", qualifiedByName = "mapVolunteerIntoAvailability")`

y meter en el método:
```
@Named("mapVolunteerIntoAvailability")
    static Volunteer mapVolunteerIntoAvailability(Volunteer volunteer) {
        return volunteer.getAvailability() == null ? null : volunteer;
    }
```

Elimina el resto de propiedades cuando se hace mapeo desde DTO a Entidad para Availability.

2024-01-03 19:19 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
Has visto la implementación? No se copia en el mapeo, ya que es un objeto anidado, y JPA con Hibernate necesita meter ese objeto para enlazarlos en base de datos.

Fíjate en el código auto generado para el mapper de Availability, que sería el que debería contener la entidad Volunteer una vez construida:

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-01-03T19:54:18+0100",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 21.0.1 (GraalVM Community)"
)
public class AvailabilityMapperImpl implements AvailabilityMapper {

    @Override
    public Availability toEntity(AvailabilityDto availabilityDto) {
        if ( availabilityDto == null ) {
            return null;
        }

        Availability.AvailabilityBuilder availability = Availability.builder();

        if ( availabilityDto.getVolunteerId() != null ) {
            availability.volunteer( AvailabilityMapper.mapVolunteerToVolunteerId( availabilityDto.getVolunteerId() ) );
        }
        Set<EWeekday> set = availabilityDto.getAvailabilityDays();
        if ( set != null ) {
            availability.availabilityDays( new HashSet<EWeekday>( set ) );
        }

        return availability.build();
    }
```

2024-01-03 19:21 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
Como podrás observar, solo hay 1 referencia al volunteer en:
`availability.volunteer( AvailabilityMapper.mapVolunteerToVolunteerId( availabilityDto.getVolunteerId() ) );`

Pero ese método se implementa de esta forma:
```
@Named("mapVolunteerToVolunteerId")
    static Volunteer mapVolunteerToVolunteerId(Integer volunteerId) {
        return Volunteer.builder().id(volunteerId).build();
    }
```

Ya que el DTO solo envía el ID, no necesita que se envíe nada más si solo se está modificando la Disponibilidad del voluntario.

2024-01-03 19:25 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(checkUserVolunteer != null && !checkUserVolunteer.getId().equals(userEntity.getId()))
El código sería o bien complejo de entender o bien verboso. pasaríamos de:
`if(checkUserVolunteer != null && !checkUserVolunteer.getId().equals(userEntity.getId()))`
a
`if(Optional.of(checkUserVolunteer).isPresent() && !checkUserVolunteer.getId().equals(userEntity.getId()))`

Sugiero mejor usar la estructura de arriba y dejarlo algo tipo:

```
// check this builder assistant id is not assigned to another volunteer
userRepository.findByVolunteer_Id(userDto.getVolunteer().getId()).ifPresent(checkUser -> {
    if(!checkUser.getId().equals(userEntity.getId()))
        throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.USER_VOLUNTEER_ALREADY_ASSIGNED);        
});
```
más legible y algo más elegante

2024-01-03 19:28 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        // map the whole User with password encoded
Los comentarios son necesarios por la complejidad algorítmica que tiene la funcionalidad de actualización de usuarios. Si te fijas en los comentarios, son esclarecedores, pues aunque se puede leer el código, es más fácil saber qué se está haciendo en cada paso.
Échale un ojo a este artículo: https://refactoring.guru/smells/comments
<img width="678" alt="image" src="https://github.com/ldcinventory/ldcgc-backend/assets/22920275/502f5e75-9a11-420e-af91-623d8b5f519b">

2024-01-03 19:54 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getBuilderAssistantId() != null) {
Hecho, y de paso he reducido algo de código, para darle mayor elegancia y legibilidad.

2024-01-03 20:01 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(category == null)
wow! bien visto! Cambiado.

2024-01-03 20:01 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(group == null)
Una vista de águila XD

Cambiado!

2024-01-03 20:05 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        if(checkUser != null && !checkUser.getId().equals(userEntity.getId()))
Cambiado el estilo a:

```
// check if the email to update is owned by other user
userRepository.findByEmail(userDto.getEmail()).ifPresent(checkUser -> {
    if(!checkUser.getId().equals(userEntity.getId()))
        throw new RequestException(HttpStatus.CONFLICT, Messages.Error.USER_ALREADY_EXIST);
    });
```

2024-01-03 20:09 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        if(userFromToken.getRole().equals(ERole.ROLE_MANAGER)) {
Normalmente estaría de acuerdo para evitar indentación, pero la alternativa es añadir verbosidad, es decir, estaríamos pasando de:

if(userFromToken.getRole().equals(ERole.ROLE_MANAGER)) {
            if(userEntity.getRole().equals(ERole.ROLE_ADMIN))
                throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.USER_PERMISSION_OTHER);
            if(userDto.getRole().equals(ERole.ROLE_ADMIN))
                throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.USER_PERMISSION_ROLE_OTHER);
        }

a:

if(userFromToken.getRole().equals(ERole.ROLE_MANAGER) && userEntity.getRole().equals(ERole.ROLE_ADMIN))
    throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.USER_PERMISSION_OTHER);
if(userFromToken.getRole().equals(ERole.ROLE_MANAGER) && userDto.getRole().equals(ERole.ROLE_ADMIN))
    throw new RequestException(HttpStatus.FORBIDDEN, Messages.Error.USER_PERMISSION_ROLE_OTHER);
        }

Teniendo en cuenta que los mensajes devueltos son diferentes, no caigo en si hay alguna opción adicional para simplificarlo más de lo que ya existe, ya que he sacado la parte común en un if "padre".

2024-01-04 10:30 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        final Integer originVolunteerId = Optional.ofNullable(userEntity.getVolunteer()).map(Volunteer::getId).orElse(null);
Por legibilidad y estilo, Me parece más elegante usar optional.

2024-01-04 10:35 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        final Integer originVolunteerId = Optional.ofNullable(userEntity.getVolunteer()).map(Volunteer::getId).orElse(null);
Hecho.

2024-01-04 10:38 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
Claro, pero eso se esta haciendo ya. Mapper de Volunteer:
![image](https://github.com/ldcinventory/ldcgc-backend/assets/55138877/061bb74a-89e8-46e2-bee6-62cbaad7447f)

La implementación está llamando al mapper de availability, el cual llama a la funcion custom que comentas. No hace falta volver a copiar availability.

Si lo que pretendes es copiar todo el objeto volunteer dentro de availability.volunteer, ¿por qué no hacerlo directamente en el mapper para dejar el servicio mas limpio?

Aparte, ¿no es redundante que un voluntario tenga availability y que esta a su vez tenga al mismo voluntario? ¿No puede dar lugar a errores de stack overflow?

2024-01-04 10:48 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
Entiendo, pero veo esto realmente redundante. Hace falta una tabla entera para los días disponibles de la semana de un voluntario? No sería más fácil tener un único campo en la tabla voluntarios?
¿Por qué el Dto solo tiene el id? Si tuviera el objeto voluntario entonces el mapeo seria mas sencillo.

2024-01-04 10:55 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        // map the whole User with password encoded
Bueno, crees que esto lo hemos hecho? "(when all other methods for simplifying the algorithm have been tried and come up short)."

Quizás se puedan sacar funciones más descriptivas¿?

2024-01-04 10:57 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
Buen punto. Lo dejo para la siguiente PR, que tengo ya en activo la rama de ausencias, disponibilidad y subida de voluntarios por excel

2024-01-04 10:58 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/VolunteerServiceImpl.java
> +        if(volunteerDto.getAvailability() != null)
Sí daría errores de stackoverflow, pero así son las uniones `@OneToOne`. De todas formas, lo dejamos para la siguiente PR, y este código lo modifico en la rama de ausencias, disponibilidad y subida de voluntarios por Excel.

2024-01-04 11:01 UTC, mindOf-L commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +        // map the whole User with password encoded
Si quieres te hago una función parrafal para cada validación 🤣 .

He tratado de hacerlo más simple, pero con el tema de los permisos a futuros pasará lo mismo. Y te lo digo por un proyecto en el que estoy que madre mía, ni 1 solo comentario y no hay por dónde cogerlo. Tampoco las funciones auto descriptivas ayudan en nada.

Si quieres, a futuros, meto un paquete validación para externalizar todo ahí. Pero eso sería para una siguiente PR. Ábrete tarea en trello 👍🏻

2024-01-04 20:03 UTC, srello commented on src/main/java/org/ldcgc/backend/service/users/impl/UserServiceImpl.java
> +            if(checkUserVolunteer != null && !checkUserVolunteer.getId().equals(userEntity.getId()))
me parece bien

2024-01-04 20:04 UTC, srello approved these changes

2024-01-04 20:05 UTC, merged